#include <stdio.h>
/*
Uses the Luhn algorithm in order to create a checksum (the last digit of the IMEI).
When IMEI's are entered into the database they can now be cut short by one digit
and the last digit will be automatically generated by this program.
The IMEI's last digit in the database can then be compared to the phone in order to verify
that the correct IMEI was entered.  If the final digit does not match there was a user error.
*/

int main()
{
//Test IMEI 49015420323751(8) with 8 being the valid checksum
long long imei = 49015420323751;
int i, num, checksum, sum=0, len=14;

//runs a loop that does math for each digit within the IMEI.  Len can be set to the correct number depending on IMEI type.
for(i=0;i<len;i++){
    //sets num to equal the right-most digit in the imei
    num=imei%10;
    //sets the right-most digit in the imei to 0. Redundant in C but may be necessary when integrated into database
    imei-=num;
    //eliminates right-most digit from the imei
    imei/=10;
    //is true for every other digit of the IMEI starting from the right side
    if(i%2 != 1){
        //doubles num, and if num becomes >=10, add the separate digits e.g. 14 becomes 1+4
        num = num*2;
        if(num>=10)
            num=num%10 + 1;
    }
    //creates a total that is equal to the sum of all digits after the algorithm is applied
    sum+=num;
}
//sets checksum to the specific integer that when added to sum, would make sum evenly divisible by 10
checksum = 10 - sum%10;
//the checksum is now valid and the following statement will output in in a compile C program
printf("%d",checksum);
    return 0;
}
